spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        group: DEFAULT_GROUP
    sentinel:
      transport:
        dashboard: localhost:8200
        port: 8719
      eager: true
    gateway:
      routes:
        - id: codearena-ai-service
          uri: lb://codearena-ai-service
          predicates:
            - Path=/api/ai/**
        - id: codearena-judge-service
          uri: lb://codearena-judge-service
          predicates:
            - Path=/api/judge/**
        - id: codearena-question-service
          uri: lb://codearena-question-service
          predicates:
            - Path=/api/question/**
        - id: codearena-search-service
          uri: lb://codearena-search-service
          predicates:
            - Path=/api/search/**
        - id: user-docs
          uri: http://localhost:8101
          predicates:
            - Path=/api/user/v3/api-docs
        - id: user-swagger
          uri: http://localhost:8101
          predicates:
            - Path=/api/user/swagger-ui.html
        - id: user-login
          uri: http://localhost:8101
          predicates:
            - Path=/api/user/login
        - id: user-register
          uri: http://localhost:8101
          predicates:
            - Path=/api/user/register
        - id: codearena-user-service
          uri: lb://codearena-user-service
          predicates:
            - Path=/api/user/**
  redis:
    database: 1
    host: localhost
    port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/codearena_db
    username: root
    password: 2771651667
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      minIdle: 20
      max-active: 200
      max-wait: 2000
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 600000
      max-evictable-idle-time-millis: 900000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      keepAlive: true
      aop-patterns: "com.springboot.template.dao.*"
      filters: stat,wall,log4j2
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: 123
        allow: 127.0.0.1
        deny:
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  application:
    name: codearena-gateway
server:
  port: 8102
knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
dubbo:
  application:
    name: codearena-gateway
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false
    group: dubbo-group
